"""Add foreign key indexes

Revision ID: 126035d81000
Revises: 8dcda7d5c27d
Create Date: 2026-06-05 23:37:49.662084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126035d81000'
down_revision: Union[str, Sequence[str], None] = '8dcda7d5c27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blocks_analysis_analysis_result_id'), 'blocks_analysis', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_detected_features_analysis_result_id'), 'detected_features', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_project_versions_project_id'), 'project_versions', ['project_id'], unique=False)
    op.create_index(op.f('ix_projects_session_id'), 'projects', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_session_id'), table_name='projects')
    op.drop_index(op.f('ix_project_versions_project_id'), table_name='project_versions')
    op.drop_index(op.f('ix_detected_features_analysis_result_id'), table_name='detected_features')
    op.drop_index(op.f('ix_blocks_analysis_analysis_result_id'), table_name='blocks_analysis')
    # ### end Alembic commands ###
