"""add_max_scattering_column

Revision ID: 8dcda7d5c27d
Revises: da1f482d9929
Create Date: 2026-06-04 01:37:53.317365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dcda7d5c27d'
down_revision: Union[str, Sequence[str], None] = 'da1f482d9929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('max_scattering', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'max_scattering')
    # ### end Alembic commands ###
