"""removed roles

Revision ID: 9a4e86d86448
Revises: 77b7640e20a2
Create Date: 2026-03-18 00:20:05.564058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a4e86d86448'
down_revision: Union[str, Sequence[str], None] = '77b7640e20a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('device_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('uix_user_session_project'), 'projects', type_='unique')
    op.create_unique_constraint('uix_device_session_project', 'projects', ['device_id', 'session_id'])
    op.drop_constraint(op.f('projects_user_id_fkey'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'user_id')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('ADMIN', 'USER', name='role'), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('projects_user_id_fkey'), 'projects', 'users', ['user_id'], ['id'])
    op.drop_constraint('uix_device_session_project', 'projects', type_='unique')
    op.create_unique_constraint(op.f('uix_user_session_project'), 'projects', ['user_id', 'session_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('projects', 'device_id')
    # ### end Alembic commands ###
