"""add_avg_metrics_and_block_aggregates

Revision ID: da1f482d9929
Revises: f1dc07104dfe
Create Date: 2026-06-03 10:57:28.383988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1f482d9929'
down_revision: Union[str, Sequence[str], None] = 'f1dc07104dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('avg_tangling', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('analysis_results', sa.Column('avg_scattering', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('analysis_results', sa.Column('total_modified_blocks', sa.Integer(), server_default='0', nullable=False))
    op.add_column('analysis_results', sa.Column('total_definition_changes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('analysis_results', sa.Column('total_feature_guarded_changes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('analysis_results', sa.Column('total_ast_pipeline_changes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'total_ast_pipeline_changes')
    op.drop_column('analysis_results', 'total_feature_guarded_changes')
    op.drop_column('analysis_results', 'total_definition_changes')
    op.drop_column('analysis_results', 'total_modified_blocks')
    op.drop_column('analysis_results', 'avg_scattering')
    op.drop_column('analysis_results', 'avg_tangling')
    # ### end Alembic commands ###
