name: Deploy to Render and Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy_render:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_URL }}
        run: curl -sSf "$DEPLOY_URL"

  deploy_vercel:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        env:
          DEPLOY_URL: ${{ secrets.VERCEL_DEPLOY_URL }}
        run: curl -sSf "$DEPLOY_URL"